name: StarMTools
version: '${version}'

main: team.starm.StarMTools
authors: [BrokenDream_Star, DeepSeek]
website: "https://starm.team/"
api-version: '26.1.2'
load: POSTWORLD
softdepend: [PlaceholderAPI]

commands:
  starmtools:
    description: "StarMTools main command"
    usage: "/starmtools reload"
  fly:
    description: "Toggle flight mode"
    usage: "/fly"
  serverinfo:
    description: "View server system information"
    usage: "/serverinfo"
  tpa:
    description: "Request to teleport to a player"
    usage: "/tpa <player>"
  tpahere:
    description: "Request a player to teleport to you"
    usage: "/tpahere <player>"
  back:
    description: "Teleport back to death point or last location"
    usage: "/back"

permissions:
  starmtool.fly:
    description: "Allows use of /fly command"
    default: op
  starmtool.serverinfo:
    description: "Allows use of /serverinfo command"
    default: op
  starmtool.tpa:
    description: "Allows use of /tpa command"
    default: true
  starmtool.tpahere:
    description: "Allows use of /tpahere command"
    default: true
  starmtool.back:
    description: "Allows use of /back command"
    default: true
